spring:
  datasource:
    driver-class-name : com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://127.0.0.1:3306/firstshopdb?useSSL=false&useUnicode=true&serverTimezone=Asia/Seoul&allowPublicKeyRetrieval=true
    username: root
    password: 9914345zx
  jpa :
    hibernate :
      ddl-auto : none
      naming :
        physical-strategy : org.hibernate.boot.model.naming.PhysicalNamingStrategyStandardImpl
#jwt:
#  secret : vmfhaltmskdlstkfkdgodyroqkfwkdbalroqkfwkdbalaaaaaaaaaaaaaaaabbbbb



